import mongoose, { Schema } from "mongoose";

const tripSchema = new mongoose.Schema(
  {
    _tripId: {
      type: String,
      required: true,
      unique: true,
    },
    tripName: {
      // Name of the trip
      type: String,
      required: true,
    },
    tripDescription: {
      // Description of the trip
      type: String,
      required: true,
      maxLength: 300,
    },
    tripType: {
      type: String,
      required: true,
      enum: ["bicycle", "trek"],
    },
    destination: {
      country: {
        type: String,
        required: true,
        trim: true,
      },
      city: {
        type: String,
        required: false,
        trim: true,
      },
    },
    route: {
      startPoint: {
        lat: {
          type: Number,
          required: true,
        },
        lng: {
          type: Number,
          required: true,
        },
        name: {
          type: String,
          required: false,
        },
      },

      endPoint: {
        lat: {
          type: Number,
          required: true,
        },
        lng: {
          type: Number,
          required: true,
        },
        name: {
          type: String,
          required: false,
        },
      },
      waypoints: [
        {
          lat: {
            type: Number,
            required: true,
          },
          lng: {
            type: Number,
            required: true,
          },
          name: {
            type: String,
            required: false,
          },
          order: {
            type: Number,
            required: true,
          },
        },
      ],
    },
    dailyBreakdown: [
      {
        day: {
          type: Number,
          required: true,
          min: 1,
        },
        distance: {
          type: Number,
          required: true,
          min: 0,
        },
        description: {
          type: String,
          required: false,
        },
        stops: [
          {
            lat: Number,
            lng: Number,
            name: String,
            description: String,
          },
        ],
      },
    ],
    totalDistance: {
      type: Number,
      required: true,
      min: 0,
    },

    totalDays: {
      type: Number,
      required: true,
      min: 1,
      max: 15,
    },

    image: {
      url: {
        type: String,
        required: false,
      },
      description: {
        type: String,
        required: false,
      },
      isGenerated: {
        type: Boolean,
        default: false, // Indicates if the image was generated by AI
      },
    },

    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    difficulty: {
      type: String,
      enum: ["קל", "בינוני", "קשה"],
      required: false,
    },
  },
  {
    timestamps: true, // Automatically manage createdAt and updatedAt fields
  }
);

// const tripSchema = new mongoose.Schema(
//   {
//     tripName: {
//       // Name of the trip
//       type: String,
//       required: true,
//     },
//   },
//   {
//     timestamps: true, // Automatically manage createdAt and updatedAt fields
//   }
// );

const Trip = mongoose.model("Trip", tripSchema);

export default Trip;
